---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
source(here::here("R/functions.R"))
```

## Results: basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset."
  )
```

## Plot of distributions

```{r}
tar_read(plot_distributions)
```

## Fitiing all metabolites

```{r}
targets::tar_read(run_all) |>
  knitr::kable(
    caption = "The results of fitting all metabolites in the lipidomics dataset."
  )
```

##Figure of model estimates

```{r}
model_results <- targets::tar_read(run_all)

model_results |> 
  filter(term =="value", std.error <= 2, estimate <= 5) |> 
  select(metabolite, model, estimate, std.error) |> 
  ggplot(aes(
    x = estimate,
    y = metabolite, 
    xmin = estimate - std.error,
    xmax = estimate + std.error
  )) +
  geom_pointrange() +
  geom_vline(xintercept =1, linetype ="dashed") +
  facet_grid(cols = vars(model))
```
